apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  annotations:
    kubernetes.io/service-account.name: jenkins

# to get the token 
# deploy in jenkins namespace 
# kubectl apply -f secret -n jenkins
# kubectl -n jenkins describe Secret mysecretname

# also for to add kubernetes server end point in jenkins go on 
#  cd /root/.kube
# take the ip and port url from config file


